### ISSUE TITLE
BUG: Can't override {{date}} settings in 'schema 1.0.1'

### ISSUE THREAD

**Issue by stoweboyd** [obsidianmd/obsidian-clipper#85] opened 2024-10-10 01:33 UTC
**Version (please complete the following information):**
 - OS: Mac
 - Browser: Chrome
 - Web Clipper version: don't know
- Obsidian version: 1.7.3

**Describe the bug**
I am trying to add a {{date}} to the note name but it seems to be overridden by 'schema 1.0.1', which I have no access to. The resulting text is `2024-10-09T21:32:03-04:00` even when I use `{{date:YYYY-MM-DD}}`. I expected a date like `2024-10-09`.

**Comment by kepano** [comment] 2024-10-10 02:14
This is a duplicate of #40. The correct use of the date filter is `{{date|date:"YYYY-MM-DD"}}`

**Closed** 2024-10-10 02:14 UTC

**Comment by stoweboyd** [comment] 2024-10-10 11:02
Thanks, that works.
