### ISSUE TITLE
BUG: cannot save to obsidian after clicking the "add" button

### ISSUE THREAD

**Issue by DZL1943** [obsidianmd/obsidian-clipper#95] opened 2024-10-17 15:07 UTC
**Version (please complete the following information):**
 - OS: [e.g. Windows] Android 13
 - Browser [e.g. Chrome, Firefox] kiwi
 - Web Clipper version: [e.g. 0.5.0] 0.9.3
- Obsidian version: [e.g. 1.7.2] 1.7.4

**Describe the bug**
A clear and concise description of what the bug is. If applicable, add screenshots to help explain your problem.

![Image_1729205855725.jpg](https://github.com/user-attachments/assets/0040fd10-629c-4760-9e29-8668144bf366)

**To reproduce**

**Expected behavior**

**Your template file**
Go to your template in Web Clipper settings and click on "Export". Attach the JSON file here, or paste the content below.

**Comment by kepano** [comment] 2024-10-18 17:30
I'm not familiar with Kiwi browser. Is this an issue that you're able to reproduce in other browsers?

**Comment by DZL1943** [comment] 2024-10-19 12:24
> I'm not familiar with Kiwi browser. Is this an issue that you're able to reproduce in other browsers?

I guess chrome-based browsers will all behave this way.

I tested the Kiwi and Lemur browsers, and both exhibit this phenomenon. These two are among the Chrome-based browsers that support extensions quite well.

However, I also tested Firefox for Android and did not encounter this issue.

**Comment by LeonelRFF** [comment] 2024-10-25 13:57
Hi, I also can't save in Obsidian with Microsoft Edge although it does work in Google Chrome, however I realized that this happens when there is a lot of highlighting, if it is only a few sentences it works.


https://github.com/user-attachments/assets/aa2b7f6b-bb60-4273-a88d-9ba91506244d

**Comment by kepano** [comment] 2024-11-14 22:13
Closing this for now as I cannot reproduce. Please try the troubleshooting steps and if you can reproduce open a new issue with steps to reproduce.

https://help.obsidian.md/web-clipper/troubleshoot

**Closed by kepano** 2024-11-14 22:13 UTC
