### ISSUE TITLE
BUG: Image links are not generated on some sites

### ISSUE THREAD

**Issue by rajesh-s** [obsidianmd/obsidian-clipper#137] opened 2024-11-11 19:44 UTC
**Version (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Web Clipper version: 0.9.4
- Obsidian version: 1.7.4

**Describe the bug**
Clipping the page below does not generate the correct links to the images. The URLs in the clip are not the same as the URLs obtained from "Open image in new tab"

**To reproduce**
1. Go to https://lilianweng.github.io/posts/2023-01-10-inference-optimization/
2. Click on Extension and "Add to Obsidian"

**Expected behavior**
Generate links to image

**Comment by kepano** [comment] 2024-11-11 19:52
This is duplicate of #119 will be fixed in 0.9.5

**Closed by kepano** 2024-11-11 19:52 UTC
