### ISSUE TITLE
直接在已导入的文档里更新，而不是新建一个文档

### ISSUE THREAD

**Issue by qiekqiek** [obsidianmd/obsidian-clipper#124] opened 2024-11-08 03:24 UTC
直接在已导入的文档里更新，而不是新建一个文档

**Comment by kepano** [comment] 2024-11-08 13:43
Please create feature requests in English, and follow the template. Based on the web translation, what you are describing should already be possible using template behavior, or is a duplicate of #93

**Closed by kepano** 2024-11-08 13:43 UTC
