### ISSUE TITLE
BUG: Can't order templates in Firefox for Android

### ISSUE THREAD

**Issue by Alezy80** [obsidianmd/obsidian-clipper#215] opened 2024-11-29 19:15 UTC
**Version:**

- OS: Android
- Browser: Firefox
- Web Clipper version: 0.10.0
- Obsidian version: 1.7.7

**Describe the bug**

In mobile Firefox I can't to change order neither of templates nor vaults. When I press on left handle of template, the trash can appeared on the right of this line, but dragging doesn't work. Sometimes there are two trash cans in the templates list.

**To reproduce**

1. Install Clipper to Firefox on Android
2. Install Obsidian clipper
3. From Firefox menu open Addons → Obsidian Web Clipper → Press Settings Gear, add some Vaults and try to reorder them.

**Comment by kepano** [comment] 2024-11-29 21:35
Duplicate of #122

**Closed** 2024-11-30 17:19 UTC
Labels: bug, duplicate
