### ISSUE TITLE
BUG: safe_name filter includes characters invalid for Obsidian name

### ISSUE THREAD

**Issue by esodesod** [obsidianmd/obsidian-clipper#100] opened 2024-10-21 11:50 UTC
Not directly a bug, but I (intially) though that `safe_name` filter supposed to result in a "**safe name**"? Maybe not limited to (only) OS specific, also produce something that is fully Obsidian compatible? Maybe something like `safe_name:obsidian`?

Example below

**Version (please complete the following information):**
 - OS: macOS
 - Browser Chrome
 - Web Clipper version: 0.9.4
- Obsidian version: 1.7.4

**Describe the bug**
Using `safe_name` filter still produces a name which is not valid as title (file name) in Obsidian, e.g. includes `#` in file name

**To reproduce**
1. Go to YouTube video for `Obsidian October 2024 — Critique your plugin #1!` (https://www.youtube.com/watch?v=g2_XEDoPF4s)
2. Try saving to a note, where it includes the title/video name, which includes `#` (in this case)

As an example, I'm using:
`{{schema:@VideoObject:uploadDate|date:"YYYY-MM-DD"}} VIDEO {{schema:@VideoObject:author}} - {{schema:@VideoObject:name|safe_name}}`

Which results in something like this in Obsidian (in this case, the `#` should not be included?)
![image](https://github.com/user-attachments/assets/d7f74495-6ab3-4464-b960-9b749cefa80f)

**Expected behavior**
A "safe name" that should be able to be used in Obsidian, without any possible issues (based on the name)

**Workaround**
Using replace filter, e.g. `{{schema:@VideoObject:uploadDate|date:"YYYY-MM-DD"}} VIDEO {{schema:@VideoObject:author}} - {{schema:@VideoObject:name|safe_name|replace:"\#":"","\!":""|trim}}`

**Your template file**
```json
{
  "schemaVersion": "0.1.0",
  "name": "YouTube with transcript",
  "behavior": "create",
  "noteContentFormat": "## About\n\ntype:: #type/video/youtube/new\n\n![{{title}}]({{url}})\n\n## Description\n\n{{schema:@VideoObject:description}}\n\n## Notes\n\nYT=\n\n\n## Transcript\n\n{{selectorHtml:.ytd-transcript-segment-list-renderer|replace:\"&nbsp;\":\" \"|join|markdown}}",
  "properties": [
    {
      "name": "created",
      "value": "{{time|date:\\\"YYYY-MM-DDTHH:mm:ssZ\\\"}}",
      "type": "datetime"
    },
    {
      "name": "reviewed",
      "value": "",
      "type": "datetime"
    },
    {
      "name": "url",
      "value": "{{url}}",
      "type": "text"
    },
    {
      "name": "title",
      "value": "{{schema:@VideoObject:name}}",
      "type": "text"
    },
    {
      "name": "channel",
      "value": "{{schema:@VideoObject:author}}",
      "type": "text"
    },
    {
      "name": "related",
      "value": "[[Videos]]",
      "type": "text"
    },
    {
      "name": "published",
      "value": "{{schema:@VideoObject:uploadDate|date:\\\"YYYY-MM-DD\\\"}}",
      "type": "datetime"
    },
    {
      "name": "duration",
      "value": "{{schema:@VideoObject:duration|replace:\\\"PT\\\",\\\"\\\",\\\"S\\\",\\\"\\\"}}",
      "type": "text"
    },
    {
      "name": "watched",
      "value": "",
      "type": "text"
    }
  ],
  "triggers": [],
  "noteNameFormat": "{{schema:@VideoObject:uploadDate|date:\"YYYY-MM-DD\"}} VIDEO {{schema:@VideoObject:author}} - {{schema:@VideoObject:name|safe_name|replace:\"\\#\":\"\",\"\\!\":\"\"|trim}}",
  "path": ""
}
```

**Comment by kepano** [comment] 2024-10-21 20:22
To clarify the issue here, the problem is only with the # character, or have you encountered others?

**Comment by esodesod** [comment] 2024-10-22 07:02
Well, I only encountered the `#` character, but now you got me curious if I could test the remaining "invalid" (Obsidian) characters as well :-).

I really don't know if this is the correct approach to "hard code a title" in combination with filters, but if I test using something like `{{title|replace:"app":"NewApp #1!^[]|"|safe_name}}` for note name, and using your post https://stephango.com/file-over-app, it seems to still produce all the invalid characters with the exception of `|` being "sanitized". I'm no coder/developer, but by the look of the regex in safe_filter, I guess it's done here somewhere? https://github.com/obsidianmd/obsidian-clipper/blob/bea800d5894876e6ef2bc0a9c57d4b443dc5e66a/src/utils/filters/safe_name.ts#L26

Might just be a "personal preference" (in my case), but I'd like a filter (or `safe_name`) to be able to produce a note name that is "safe to use in Obsidian"; meaning all characters that possibly could produce issues within Obsidian are sanitized, if that makes sense.


![image](https://github.com/user-attachments/assets/bb33fcb4-4998-43ef-a5e9-4fd04e10490c)
![image](https://github.com/user-attachments/assets/2afee2e6-91ac-450d-88f6-716d02c0597d)

**Comment by Qloulia** [comment] 2024-10-23 00:37
same thing happened to me! In my case it's the character ' | '

**Comment by yeliaBdE** [comment] 2024-11-01 17:41
I just sat down with a test note that contained a link to itself and found that attempting to add the following characters to a note's name resulted in the red error banner:

# ^ [ ] \ | : /

Every other non-alphanumeric character represented on my IBM Model M clone presented no problem and the MacOS filesystem swallowed it all, as you can see from the resulting filename: "abc`~!@$%&*()-_=+{};'",<.>.md"

I then sent myself an email with the following subject: Testing `~!@#$%^&*()_+-=[]\{}|;':",./<>?

Then, clipping that email using the default template and changing its Note Name field to be: {{title|safe_name}} it produced a note file with the following filename: "Testing `~!@#$%^&()_+-=[]{};',..md"

Based on all this, it appears that the characters missing from safe_name are:

# ^ [ ]

But I have a question about all this. If I filter note names using a revised version of safe_name that adds in the above characters, does that mean that those notes would be usable/linkable in *all* Obsidian implementations on *all* supported platforms? I'm thinking of different platforms all getting synced from Obsidian Sync.

If the answer is yes--cool! However, that does beg the question: How can a regular user ensure they do not use these problematic characters in the names of the notes that they create themselves?

If the answer, however, is no, I have to ask: Why not?

On a possibly related note, it seems that a similar situation would occur with properties, as I managed to web-clip my way into unusable properties due to some character-related issue in the "title" property. Filtering the title with safe_name in the Properties section of the template did the trick, but that feels like the wrong solution, as I imagine this is more a matter of characters either not being escaped in a property-friendly way, or the set of characters that can't be used within properties is likely smaller than that of the set of problematic characters for note names, meaning safe_name would overly restrict something that doesn't need that level of restriction.

Anyway, those are my thoughts; hopefully they're helpful.

**Comment by kepano** [comment] 2024-11-11 20:55
Should be fixed in 0.9.5

**Closed by kepano** 2024-11-11 20:55 UTC

**Comment by isaacdudek** [comment] 2024-11-14 15:02
It looks like this issue was fixed for the clipped file names, but the same logic wasn't applied to the actual [safe_name filter](https://github.com/obsidianmd/obsidian-clipper/blob/main/src/utils/filters/safe_name.ts). I imagine the transformations made by those two functions should match?

**Comment by kepano** [comment] 2024-11-14 16:02
Oops missed that. Will be fixed in the next update.

**Comment by yeliaBdE** [comment] 2024-11-17 13:29
> Oops missed that. Will be fixed in the next update.

Is there a separate issue to track that fix, or should this issue be reopened?

**Comment by kepano** [comment] 2024-11-17 14:47
it should be in 0.9.7
