### ISSUE TITLE
BUG: Disabling Models in interpreter doesn't work

### ISSUE THREAD

**Issue by iLeif-de** [obsidianmd/obsidian-clipper#220] opened 2024-12-01 12:38 UTC
**Version (please complete the following information):**

- OS: MacOS 15.1.1
- Browser Safari, Chrome
- Web Clipper version: 0.10.0
- Obsidian version: 1.7.7

**Describe the bug**

When disabling models in the settings of the interpreter section. they will be still shown in the clipping popup and again in the setting the are enabled

**Expected behavior**

When models are disabled the shouldn't shown 
**URLs where the bug occurs**

Any specific web pages where the bug can be replicated.

**To reproduce**

Go to the interpreter settings, disable models and check again

**Your template file**
default + interpreter settings with openai key and local ollama

If you are using a custom template (i.e. not the Default template). Go to Web Clipper settings and click **More** → **Copy as JSON**. Paste the JSON code below.

```json
{
  "schemaVersion": "0.1.0",
  "name": "Default",
  "behavior": "create",
  "noteContentFormat": "{{\"a summary of the page in German\"|blockquote}}\n\n{{content}}\n\n---\nOrdner: `=this.file.folder`",
  "properties": [
    {
      "name": "title",
      "value": "{{title}}",
      "type": "text"
    },
    {
      "name": "source",
      "value": "{{url}}",
      "type": "text"
    },
    {
      "name": "author",
      "value": "{{author|split:\\\", \\\"|wikilink|join}}",
      "type": "multitext"
    },
    {
      "name": "published",
      "value": "{{published|date:\\\"DD.MM.YY\\\"}}",
      "type": "date"
    },
    {
      "name": "erstellt",
      "value": "{{date|date:\\\"DD.MM.YY\\\"}}",
      "type": "text"
    },
    {
      "name": "description",
      "value": "{{description}}",
      "type": "text"
    },
    {
      "name": "tags",
      "value": "clippings",
      "type": "multitext"
    },
    {
      "name": "geändert",
      "value": "{{date|date:\\\"DD.MM.YY\\\"}}",
      "type": "text"
    }
  ],
  "triggers": [],
  "noteNameFormat": "{{title}}",
  "path": "18 Clippings"
}```

**Comment by kepano** [comment] 2024-12-01 14:26
Duplicate of #211. The fix is already implemented and will be in the next version.

**Closed** 2024-12-01 14:26 UTC
Labels: bug, duplicate
