### ISSUE TITLE
Since the new update, obsidian restart on mobile when the uri is sent

### ISSUE THREAD

**Issue by MelodyDuplaix** [obsidianmd/obsidian-clipper#54] opened 2024-09-20 23:32 UTC
I update the extension on my mobile browser. Since that, every time I try to clip a page, the obsidian app restart and so the page is not clipped.

I try with the Save "clipped note without opening it" option enabled and disabled and it's the same.

I didn't try with the Early access features enabled because I'm not an insider. But before the update, all worked fine.

**Comment by kepano** [comment] 2024-09-21 02:56
What browser are you using?

**Comment by MelodyDuplaix** [comment] 2024-09-21 07:10
Simply the Firefox mobile browser.

**Comment by kepano** [comment] 2024-09-21 07:47
Does the problem occur with every page or only some pages? I would recommend using Obsidian 1.7.2+ as it sounds like this is a duplicate of #56.

**Comment by MelodyDuplaix** [comment] 2024-09-21 08:06
No, it's occur with every page, even very small content. And the same pages worked fine before the update.

**Comment by kepano** [comment] 2024-09-21 13:15
Before which update?

**Comment by MelodyDuplaix** [comment] 2024-09-21 13:21
It worked fine with the version 0.4.8 of the extension and not with 0.5

**Comment by MelodyDuplaix** [comment] 2024-09-21 16:04
It's very strange because I just tried with firefox nightly and It work.

**Comment by MelodyDuplaix** [comment] 2024-09-21 16:15
This appears to have been an unknown temporary bug. I completely reinstalled Firefox and not just the extension and it now works again.

**Closed** 2024-09-21 17:11 UTC
